version: '3.3'

services:
  web:
    build:
      context: ./web
    container_name: php-web
    volumes:
      - ./web:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data: